<a href="https://colab.research.google.com/github/MarcosMza/python-ds-introduccion-con-numpy/blob/main/Python_Data_Science_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <font color=green> PYTHON PARA DATA SCIENCE - NUMPY
---

# <font color=green> 1. INTRODUCCIÓN A PYTHON
---

# 1.1 Introducción

> Python es un lenguaje de programación de alto nivel con soporte a múltiples paradigmas de programación. Es un proyecto *open source* y desde su surgimiento, en 1991, viene convirtiéndose en uno de los lenguajes de programación interpretados más populares.
>
> En los últimos años Python desarrolló una comunidad activa de procesamiento científico y análisis de datos y viene destacándose como uno de los lenguajes más relevantes cuando el asunto es ciencia de datos y machine learning, tanto en el entorno acadêmico como también en el entorno laboral.

# 1.2 Instalación y entorno de trabajo

### Instalación Local

### https://www.python.org/downloads/
### o
### https://www.anaconda.com/distribution/

### Google Colaboratory

### https://colab.research.google.com

### Verificando versión

In [ ]:
!python -V

Python 3.10.12


# 1.3 Trabajando con Numpy

In [ ]:
# Biblioteca 'Numpy' uno de los paquetes más importante para el procesamiento numérico en python
import numpy as np

In [ ]:
# En este paso lo que realizamos es a travez de la libreria numpy,poder acceder al archivo km.txt
# Creamos la variable km y con el método -load- cargamos el archivo
km = np.loadtxt('carros-km.txt', dtype= int)

In [ ]:
km

array([ 44410,   5712,  37123,      0,  25757,  10728,      0,  77599,
        99197,  37978,  12859,   8052,  89773,      0,  41457, 115607,
        46449,      0,  37086,  15173, 101193,      0,  98079, 102959,
            0,      0,   5795,      0,  58848,  94381,  30163,  53332,
        17720,  33808,  90684,  43975,      0,      0,   5526,      0,
        93415,  40762,      0,  86302,      0,   9755,  69945,   2395,
            0,  80349,  85554,  50496,  67716,  93947,  35345,  81007,
       119513,      0,      0,      0,      0,      0, 118895,  48509,
       100912,  95649,      0,  90495,      0,  29132,  23802,  84992,
        54395,  26731,  44329, 118236, 113808,    610,      0,      0,
        12887,  79607,  90924,  42733,      0,      0, 117714, 113885,
            0,  30511,  74867, 119760,   8356,  64247,  88661,   4539,
       110116,  33215,  92001,      0,  81708,  70641,      0,  91277,
        26544,  52596,  47503,  89056,  28834, 110564,  56638,  17357,
      

In [ ]:
# Cargamos el archivo externo años con el método -loadtxt-
años = np.loadtxt('carros-años.txt', dtype= int)

In [ ]:
años

array([2003, 1991, 1990, 2020, 2006, 2012, 2020, 2009, 2010, 2011, 2002,
       2007, 2001, 2020, 2009, 2016, 2012, 2020, 2016, 2017, 2002, 2020,
       1994, 1991, 2020, 2020, 2016, 2020, 2002, 1991, 1997, 1995, 2018,
       1991, 2014, 1995, 2020, 2020, 2009, 2020, 2013, 2003, 2020, 2002,
       2020, 2002, 2004, 2001, 2020, 2003, 2009, 2006, 2000, 2006, 2010,
       1994, 2007, 2020, 2020, 2020, 2020, 2020, 2017, 2011, 2001, 1996,
       2020, 1994, 2020, 2007, 1994, 2007, 1997, 2006, 2013, 1994, 2008,
       2008, 2020, 2020, 1999, 2007, 1993, 1995, 2020, 2020, 2016, 2011,
       2020, 2002, 2013, 2017, 2016, 2008, 2018, 2003, 2003, 2004, 2010,
       2020, 2006, 2001, 2020, 2015, 2018, 2017, 1992, 2001, 1993, 1995,
       2003, 2014, 2008, 2013, 2020, 2017, 2020, 2020, 2006, 2015, 2007,
       2005, 2017, 1998, 2020, 1999, 2020, 2009, 2003, 1994, 2020, 1994,
       2020, 2015, 1996, 1997, 1993, 2020, 1992, 1995, 2020, 1990, 2020,
       2020, 1991, 1990, 2012, 2007, 2013, 2000, 20

### Obtener el promedio de kilometros recorridos por año

In [ ]:
# Con esta formula obtenemos los km al día de la fecha
# promedio = km del vehículo / (año en el que estamos - el año de fabricación)
km_promedio = km / (2023 - años)

In [ ]:
km_promedio

array([2.22050000e+03, 1.78500000e+02, 1.12493939e+03, 0.00000000e+00,
       1.51511765e+03, 9.75272727e+02, 0.00000000e+00, 5.54278571e+03,
       7.63053846e+03, 3.16483333e+03, 6.12333333e+02, 5.03250000e+02,
       4.08059091e+03, 0.00000000e+00, 2.96121429e+03, 1.65152857e+04,
       4.22263636e+03, 0.00000000e+00, 5.29800000e+03, 2.52883333e+03,
       4.81871429e+03, 0.00000000e+00, 3.38203448e+03, 3.21746875e+03,
       0.00000000e+00, 0.00000000e+00, 8.27857143e+02, 0.00000000e+00,
       2.80228571e+03, 2.94940625e+03, 1.16011538e+03, 1.90471429e+03,
       3.54400000e+03, 1.05650000e+03, 1.00760000e+04, 1.57053571e+03,
       0.00000000e+00, 0.00000000e+00, 3.94714286e+02, 0.00000000e+00,
       9.34150000e+03, 2.03810000e+03, 0.00000000e+00, 4.10961905e+03,
       0.00000000e+00, 4.64523810e+02, 3.68131579e+03, 1.08863636e+02,
       0.00000000e+00, 4.01745000e+03, 6.11100000e+03, 2.97035294e+03,
       2.94417391e+03, 5.52629412e+03, 2.71884615e+03, 2.79334483e+03,
      

In [ ]:
type(km_promedio)

numpy.ndarray

# <font color=green> 2. CARACTERÍSTICAS BÁSICAS DEL LENGUAJE
---

# 2.1 Operaciones matemáticas

### Operadores aritméticos: $+$, $-$, $*$, $/$, $**$, $\%$, $//$

### Suma ($+$)

In [ ]:
2 + 2

4

### Resta ($-$)

In [ ]:
4 - 2

2

### Multiplicación ($*$)

In [ ]:
2 * 3

6

### División ($/$) y ($//$)
La operación división siempre devuelve un número con punto decimal

In [ ]:
# Cuando tenemos una división con resultado decimal, quiere decir que la división tiene resto
10 / 3

3.3333333333333335

In [ ]:
# Cuando utilizamos // lo que hace es traerme la parte entera de la división,
# es por eso que solo me trae el 3 como resultado
10 // 3

3

### Exponenciación ($**$)

In [ ]:
# Esta función es el número elevado al exponente que deseamos buscar
2 ** 3

8

### Resto de la división ($\%$)

In [ ]:
# Con esta función lo que nos trae es el resto de la división
10 % 3

1

In [ ]:
10 % 2

0

### Expresiones matemáticas

In [ ]:
# En estos casos cumple con el orden de prioridad según reglas matemáticas
5 * 2 + 3 * 2

16

In [ ]:
(5 * 2) + (3 * 2)

16

In [ ]:
# Cuando aplicamos () tiene orden de prioridad para poder realizar la operación
5 * (2 + 3) * 2

50

### La variable _

En el modo interactivo, el último resultado impreso en pantalla es atribuído a la variable _

In [2]:
# Este operador lo que realiza es almacenar el último resultado
5 * 2

10

In [3]:
# El _ será tratado como un número
_ + 3 * 2

16

In [4]:
_ / 2

8.0

# 2.2 Variables

### Nombres de variables

- Nombres de variables pueden comenzar con letras (a - z, A - Z) o con el símbolo *underscore* (_):

    > Altura
    >
    > _peso
    
- El resto del nombre puede contener letras, números o el símbolo "_":

    > nombre_de_variable
    >
    > _valor
    >
    > dia_28_11_
    

- Los nombres son *case sensitive*:

    > Nombre_De_Variable $\ne$ nombre_de_variable $\ne$ NOMBRE_DE_VARIABLE
    
### <font color=red>Observaciones:
- Existen algumas palabras reservadas del lenguaje que no pueden ser utilizadas como nombres de variables:

| |Lista de palabras <br>reservadas en Python| |
|:-------------:|:------------:|:-------------:|
| and           | as           | not           |
| assert        | finally      | or            |
| break         | for          | pass          |
| class         | from         | nonlocal      |
| continue      | global       | raise         |
| def           | if           | return        |
| del           | import       | try           |
| elif          | in           | while         |
| else          | is           | with          |
| except        | lambda       | yield         |
| False         | True         | None          |

### Declaración de variables

### Operadores de asignación: $=$, $+=$, $-=$, $*=$, $/=$, $**=$, $\%=$, $//=$

In [ ]:
# Creamos Variables
año_actual = 2023
año_fabricacion = 2003
km_total = 44410.0

In [ ]:
año_actual

2023

In [ ]:
año_fabricacion

2003

In [ ]:
km_total

44410.0

# $$km_{promedio} = \frac {km_{total}}{(Año_{actual} - Año_{fabricación})}$$

### Operaciones con variables

In [ ]:
# Creamos la variable para obtener el promedio y realizamos el calculo
km_promedio = km_total / (año_actual - año_fabricacion)
km_promedio

2220.5

In [ ]:
# vamos a realizarlo todo junto como en los casos de programación real
año_actual = 2023
año_fabricacion = 2003
km_total = 44410.0
km_promedio = km_total / (año_actual - año_fabricacion)
km_promedio

2220.5

In [ ]:
# teniendo en cuanta que tenemos el km promedio, lo que calcularemos es cuantos
# km tendría el año siguiente, eso lo hacemos teniendo en cuanta los datos obtenidos

año_actual = 2023
año_fabricacion = 2003
km_total = 44410.0
km_promedio = km_total / (año_actual - año_fabricacion)

# se reemplaza el valor de km_total por uno nuevo que es el que obtenemos para el siguiente año 2024

km_total = km_total + km_promedio
km_total

46630.5

In [ ]:
año_actual = 2023
año_fabricacion = 2003
km_total = 44410.0
km_promedio = km_total / (año_actual - año_fabricacion)

# en este caso utilizamos el operador '+=' (cuando lo que vamos a sumar es la misma variable)

km_total += km_promedio
km_total

46630.5

### Conclusión:
```
"valor = valor + 1" es equivalente a "valor += 1"
```

### Declaración múltiple

In [ ]:
# Otra forma de declarar variables
año_actual, año_fabricacion, km_total = 2023, 2003, 44410.0

In [ ]:
año_actual

2023

In [ ]:
año_fabricacion

2003

In [ ]:
km_total

44410.0

#Resumen de lo que hemos visto


In [5]:
A = 1
B = 2
C = 3
# Es equivalente a:
A, B, C = 1, 2, 3

In [ ]:
# tener en cuanta que no hemos declarado las variables suma y valor es a modo de ejemplo
suma = suma + valor
# Es equivalente a:
suma += valor

# 2.3 Tipos de datos

Los tipos de datos especifican como números y caracteres estarán guardados y manipulados dentro de un programa. Los tipos de datos básicos en Python son:

1. **Números**
    1. ***int*** - Enteros
    - ***float*** - Decimales
- **Booleanos** - Contiene valores True o False. Esencial cuando comenzamos a trabajar con declaraciones condicionales
- ***Strings*** - Secuencia de uno o más caracteres que puede incluir letras, números y otros tipos de caracteres. Representa un texto.
- **None** - Representa la ausencia de valor

### Números

In [ ]:
año_actual = 2023

In [ ]:
type(año_actual)

int

In [ ]:
km_total = 44410.0

In [ ]:
type(km_total)

float

### Booleanos

In [ ]:
zero_km = True

In [ ]:
type(zero_km)

bool

In [ ]:
zero_km = False

In [ ]:
type(zero_km)

bool

### Strings

In [ ]:
nombre = 'Marcos Lana'
nombre

'Marcos Lana'

In [ ]:
# Otra forma de realizarlo
nombre = "Marcos Lana"
nombre

'Marcos Lana'

In [ ]:
# Cuando combinamos "" con '', lo que hace es tomarme las "" como un caracter
nombre = 'Marcos "Lana"'
nombre

'Marcos "Lana"'

In [ ]:
# Cuando combinamos '' con "", lo que hace es tomarme las '' como un caracter
nombre = "Marcos 'Lana'"
nombre

"Marcos 'Lana'"

In [ ]:
# Creamos un texto con varias líneas, nos da como resultado \n que quiere decir
#que tenemos salto de línea
vehiculo = '''
Nombre
Edad
Nota
'''
vehiculo

'\nNombre\nEdad\nNota\n'

In [ ]:
type(vehiculo)

str

### None

In [ ]:
# Si bien creamos la variables, pero al ser una variable = None, obtenemos un valor
# nulo, porque representa la ausencia de valor
kilometraje = None
kilometraje

In [ ]:
type (kilometraje)

NoneType

# 2.4 Conversión de tipos

In [ ]:
a = 10
b = 20
c = 'Python es'
d = 'genial'

In [ ]:
type(a)

int

In [ ]:
type(b)

int

In [ ]:
type(c)

str

In [ ]:
type(d)

str

In [ ]:
# realizamos la suma de dos variables int
a + b

30

In [ ]:
# realizamos la suma de dos variables str (a esta suma se la conoce como concatenar)
c + d

'Python esgenial'

In [ ]:
# realizamos la suma de dos variables de type diferentes (a esta suma se la conoce como concatenar)
# c + a (lo que tenemos que hacer es convertir una de las variables)

### Conversiones de tipo

Funciones int(), float(), str()

In [ ]:
# En el ejercicio anterior 'a' era un 'int', lo vamos a convertir en un 'str'
str(a)

'10'

In [ ]:
type(str(a))

str

In [ ]:
# Ahora realizamos la suma ya que las dos variables son del mismo type
c + str(a)

'Python es10'

In [ ]:
# Ahora vamos a convertir 'a' que es un 'int' en un 'float'
float(a)

10.0

In [ ]:
# Ahora vamos a convertir un numero decimal en entero
var = 3.141592

In [ ]:
# Lo que hace es regresar la parte entera por eso nos arroja el '3'
int(var)

3

In [ ]:
# Ejercicio ejemplo:
text = 'El kilometraje promedio del vehículo es '
Km = 100000
Año_actual = 2020
Año_fabricacion = 2000

In [ ]:
# realizamos la cuenta del promedio convirtiendo un 'float' a 'int'
Km_promedio = int(Km /(Año_actual - Año_fabricacion))
Km_promedio

5000

In [ ]:
# Concatenamos (sumamos) dos variables de diferentes type, realizando la conversión de una de ellas
text + str(Km_promedio) + ' km'

'El kilometraje promedio del vehículo es 5000 km'

In [ ]:
# de una forma mas reducida lo podemos hacer así:
text + str(int(Km /(Año_actual - Año_fabricacion))) + ' km'

# Observamos que se han realizado dos conversiones. En la primera,
# el resultado de la operación (float) es convertido en un entero (int) y luego,
# el dato de tipo entero es convertido en una string (str).

'El kilometraje promedio del vehículo es 5000 km'

# 2.5 Indentación, comentarios y formatación de *strings*

### Indentación

En el lenguaje Python los programas son estructurados por medio de indentación. En cualquier lenguaje de programación la práctica de colocar indentación es bastante útil, facilitando la lectura y también el mantenimiento del código. En Python la indentación no es solamente una cuestión de organización y estilo, sino que es un requisito del lenguaje.

In [ ]:
año_actual = 2020
año_fabricacion = 2020

if (año_actual == año_fabricacion):
    print('Verdadero')
else:
    print('Falso')

Verdadero


### Comentarios

Comentarios son extremamente importantes en un programa. Consiste en un texto que describe lo que el programa o una parte específica del programa está haciendo. Los comentarios son ignorados por el interpretador Python.

Podemos tener comentarios de una única linea o de múltiples líneas.

In [ ]:
# Esto es un comentario
año_actual = 2020
año_actual

In [ ]:
# Esto
# es un
# comentario
año_actual = 2020
año_actual

In [ ]:
'''Esto es un
comentario'''
año_actual = 2020
año_actual

In [ ]:
# Definiendo variables
año_actual = 2020
año_fabricacion = 2020

'''
Estructura condicional que vamos
a aprender la próxima clase
'''
if (año_actual == año_fabricacion):   # Probando si la condición es verdadera
    print('Verdadero')
else:                               # Probando si la condición es falsa
    print('Falso')

### Formatación de *strings*

## *str.format()*

https://docs.python.org/3.6/library/stdtypes.html#str.format

In [ ]:
# El método .format() permite la designación de nombres para los argumentos
# lo vamos a utilizar para poder imprimir variables de diferentes tipos y obtener todo en un str
print('Hola, {}'.format('Marcos'))

Hola, Marcos


In [ ]:
# con este formato utilizamos {} para que reemplecen la variable dentro de metodo format
# tener en cuenta que el orden con el que coloquemos dentro del método es lo que nos arroja
print('Hola, {}! Esta es su visita numero {}'.format('Marcos',25))

Hola, Marcos! Esta es su visita numero 25


In [ ]:
# otra forma puede ser con la creación de variables dentro del método,
# de esta forma no depende del orden de las variables, dentro de los {} colocamos la variable
print('Hola, {nombre}! Esta es tu juego número {juego}'.format(juego=25,nombre='Marcos'))

Hola, Marcos! Esta es tu juego numero 25


## *f-Strings*

https://docs.python.org/3.6/reference/lexical_analysis.html#f-strings

In [ ]:
# declaramos las variables
nombre = 'Marcos'
juego = 25

In [ ]:
# en este caso, colocamos la 'f' al comienzo y lo que hace el método es buscar el contenido
# de las variables antes declaradas y tomar su valor
print(f'Hola, {nombre}! Esta es tu juego número {juego}')

Hola, Marcos! Esta es tu juego número 25


# <font color=green> 3. TRABAJANDO CON LISTAS
---

# 3.1 Creando listas

Listas son secuencias **mutables** que son utilizadas para guardar colecciones de objetos, generalmente homogéneos. Pueden ser construídas de varias formas:
```
- Utilizando un par de corchetes: [ ], [ 1 ]
- Utilizando un par de corchetes con objetos separados por comas: [ 1, 2, 3 ]
```

In [ ]:
Accesorios = ['Cerraduras eléctricas', 'Piloto automático', 'Asientos de cuero', 'Aire acondicionado', 'Sensor de estacionamiento', 'Sensor de lluvia']
Accesorios

['Cerraduras eléctricas',
 'Piloto automático',
 'Asientos de cuero',
 'Aire acondicionado',
 'Sensor de estacionamiento',
 'Sensor de lluvia']

In [ ]:
# vemos que al momento de solicitar el tipo de dato, nos arroja 'list'
type(Accesorios)

list

### Lista con tipos de datos variados

In [ ]:
vehiculo_1 = ['Jetta Variant', 'Motor 4.0 Turbo', 2003, 44410.0, False, ['Cerraduras eléctricas', 'Piloto automático'], 88078.64]
vehiculo_2 = ['Passat', 'Motor Diesel', 1991, 5712.0, False, ['Central multimedia', 'Frenos ABS'], 106161.94]

In [ ]:
# se observa que los elementos de las listas pueden ser variados, incluso tener listas dentro de listas
vehiculo_1

['Jetta Variant',
 'Motor 4.0 Turbo',
 2003,
 44410.0,
 False,
 ['Cerraduras eléctricas', 'Piloto automático'],
 88078.64]

In [ ]:
vehiculo_2

['Passat',
 'Motor Diesel',
 1991,
 5712.0,
 False,
 ['Central multimedia', 'Frenos ABS'],
 106161.94]

In [ ]:
# podemos tener una lista donde sus elementos sean más listas
vehiculos = [vehiculo_1,vehiculo_2]
vehiculos

[['Jetta Variant',
  'Motor 4.0 Turbo',
  2003,
  44410.0,
  False,
  ['Cerraduras eléctricas', 'Piloto automático'],
  88078.64],
 ['Passat',
  'Motor Diesel',
  1991,
  5712.0,
  False,
  ['Central multimedia', 'Frenos ABS'],
  106161.94]]

# 3.2 Operaciones con listas

https://docs.python.org/3.6/library/stdtypes.html#common-sequence-operations

## *x in A*

Devuelve **True** si un elemento de la lista *A es igual a x*.

In [ ]:
Accesorios

['Cerraduras eléctricas',
 'Piloto automático',
 'Asientos de cuero',
 'Aire acondicionado',
 'Sensor de estacionamiento',
 'Sensor de lluvia']

In [ ]:
# con el operador 'in' lo que hacemos es preguntar si 'x' elemento pertenece o no a la lista
'Cerraduras eléctricas' in Accesorios

True

In [ ]:
'4 X 4' in Accesorios

False

In [ ]:
# otra de la forma de preguntar es con una negación
'Cerraduras eléctricas' not in Accesorios

False

In [ ]:
'4 X 4' not in Accesorios

True

In [ ]:
# otro ejemplo:
Auto = [
'Jetta Variant',
 'Motor 4.0 Turbo',
 2003,
 44410.0,
 False,
 ['Llantas de aleación', 'Cerraduras eléctricas', 'Piloto automático'],
 88078.64
]

In [ ]:
# en este caso vamos a tener False como resultado, ya que preguntamos si 2003
# pertenece a la lista Auto, pero como 'str' y es un 'int'
'2003' in Auto

False

In [ ]:
# en este caso también es False, ya que es un elemento que pertenece a un elemento lista dentro de la lista Auto
'Llantas de aleación' in Auto

False

In [ ]:
# en este caso obtenemos True por que es un elemento de la lista Auto
False in Auto

True

## *A + B*

Concatena las listas *A y B*.

In [ ]:
A = ['Cerraduras eléctricas', 'Piloto automático', 'Asientos de cuero']
B = ['Aire acondicionado', 'Sensor de estacionamiento', 'Sensor de lluvia']

In [ ]:
# al utilizar el operador + con listas, lo que realiza es concatenar (sumar) los elementos de ambas
A + B

['Cerraduras eléctricas',
 'Piloto automático',
 'Asientos de cuero',
 'Aire acondicionado',
 'Sensor de estacionamiento',
 'Sensor de lluvia']

## *len(A)*

Tamaño de la lista A.

In [ ]:
# El tamaño va a quedar determinado por la cantidad de elementos de la lista
len(Accesorios)

6

# 3.3 Selecciones en listas

## *A[ n ]*

Devuelve el n-ésimo objeto de la lista *A*.

<font color=red>**Observación:**</font> Listas tienen indexación con inicio en cero.

In [ ]:
# Utilizamos la lista Accesorios
Accesorios

['Cerraduras eléctricas',
 'Piloto automático',
 'Asientos de cuero',
 'Aire acondicionado',
 'Sensor de estacionamiento',
 'Sensor de lluvia']

In [ ]:
# Con este método lo que vamos a realizar es extraer uno o varios elementos de la lista
# en este caso vamos a extraer el primer elemento de la lista
# tener en cuanta que la posición de los valores comienza en 0
Accesorios[0]

'Cerraduras eléctricas'

In [ ]:
# Extraeremos el valor de la segunda posición
Accesorios[1]

'Piloto automático'

In [ ]:
# En caso de querer extraer el ultimo elemento, debido a que pueden ser muchos elementos
# vamos a utilizar -1 para que extraiga el ultimo elemento de la lista
Accesorios[-1]

'Sensor de lluvia'

In [ ]:
# recordamos que vehículos es una lista que sus elementos son listas
vehiculos

[['Jetta Variant',
  'Motor 4.0 Turbo',
  2003,
  44410.0,
  False,
  ['Cerraduras eléctricas', 'Piloto automático'],
  88078.64],
 ['Passat',
  'Motor Diesel',
  1991,
  5712.0,
  False,
  ['Central multimedia', 'Frenos ABS'],
  106161.94]]

In [ ]:
# extraemos el primero valor de la lista vehículo, este primer elemento contiene otra lista
vehiculos[0]

['Jetta Variant',
 'Motor 4.0 Turbo',
 2003,
 44410.0,
 False,
 ['Cerraduras eléctricas', 'Piloto automático'],
 88078.64]

In [ ]:
# para obtener o extraer el 1er elemento del la lista extraída como 1er elemento de la lista vehículos
# siempre hay que respetar el orden
vehiculos[0][0]

'Jetta Variant'

In [ ]:
# para obtener o extraer el penultimo elemento del la lista estraida como 1er elemento de la lista vehiculos
# en este caso vamos a obtener otra lista, por lo que el penúltimo elemento es otra lista
vehiculos[0][-2]

['Cerraduras eléctricas', 'Piloto automático']

In [ ]:
# para extraer un elemento de la lista obtenida en el ultimo ejemplo
# recordar seguir el orden
vehiculos[0][-2][1]

'Piloto automático'

## *A[ i : j ]*

Recorta la lista A desde el índice i hasta j. En este recorte el elemento con índice i **es incluído** y el elemento con índice j **no es incluído** en el resultado.

In [ ]:
Accesorios

['Cerraduras eléctricas',
 'Piloto automático',
 'Asientos de cuero',
 'Aire acondicionado',
 'Sensor de estacionamiento',
 'Sensor de lluvia']

In [ ]:
# Tener en cuanta que vamos a extraer varios elementos de la lista, no olvidar que el último no lo incluye
Accesorios[2:5]

['Asientos de cuero', 'Aire acondicionado', 'Sensor de estacionamiento']

In [ ]:
# para poder extraer los elementos desde la posición indicada hasta el final
# colocamos los : y luego nada para traer hasta el último dato de la lista
Accesorios[2:]

['Asientos de cuero',
 'Aire acondicionado',
 'Sensor de estacionamiento',
 'Sensor de lluvia']

In [ ]:
# de igual modo lo realizamos si queremos desde el primer elemento de la lista hasta el determinado
Accesorios[:5]

['Cerraduras eléctricas',
 'Piloto automático',
 'Asientos de cuero',
 'Aire acondicionado',
 'Sensor de estacionamiento']

In [ ]:
# vemos otro ejemplo:
letras = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']

In [ ]:
# para obtener ['A', 'B']
letras[:2]

['A', 'B']

In [ ]:
# para obtener ['C', 'D', 'E']
letras[2:5]

['C', 'D', 'E']

In [ ]:
# para obtener ['F', 'G', 'H']
letras[-3:]

['F', 'G', 'H']

In [ ]:
# vemos otro ejemplo:
carros = [
    [
        'Jetta Variant',
        'Motor 4.0 Turbo',
        2003,
        False,
        ['Llantas de aleación', 'Cerraduras eléctricas', 'Piloto automático']
    ],
    [
        'Passat',
        'Motor Diesel',
        1991,
        True,
        ['Central multimedia', 'Techo panorámico', 'Frenos ABS']
    ]
]
# vamos a buscar los elementos: True, 'Techo panorámico' y ['Llantas de aleación', 'Cerraduras eléctricas', 'Piloto automático']

In [ ]:
# Extraemos True
carros[1][-2]

True

In [ ]:
# Extraemos 'Techo panorámico'
carros[1][-1][1]

'Techo panorámico'

In [ ]:
# Extraemos ['Llantas de aleación', 'Cerraduras eléctricas', 'Piloto automático']
carros[0][-1]

['Llantas de aleación', 'Cerraduras eléctricas', 'Piloto automático']

# 3.4 Métodos en listas

https://docs.python.org/3.6/library/stdtypes.html#mutable-sequence-types

## *A.sort()*

Ordena la lista *A*.

In [ ]:
Accesorios

['Cerraduras eléctricas',
 'Piloto automático',
 'Asientos de cuero',
 'Aire acondicionado',
 'Sensor de estacionamiento',
 'Sensor de lluvia']

In [ ]:
# Ordena los elementos alfabéticamente
Accesorios.sort()
Accesorios

['Aire acondicionado',
 'Asientos de cuero',
 'Cerraduras eléctricas',
 'Piloto automático',
 'Sensor de estacionamiento',
 'Sensor de lluvia']

## *A.append(x)*

Añade el elemento *x al final de la lista A*

In [ ]:
Accesorios.append('4 X 4')
Accesorios

['Aire acondicionado',
 'Asientos de cuero',
 'Cerraduras eléctricas',
 'Piloto automático',
 'Sensor de estacionamiento',
 'Sensor de lluvia',
 '4 X 4']

## *A.pop(i)*

Elimina y devuelve el elemento de índice i de la lista *A*.

<font color=red>**Observación:**</font> Por *defecto* el método *pop()* elimina y devuelve el último elemento de una lista.

In [ ]:
# al no colocar un elemento determinado, elimina el último agregado
Accesorios.pop()

'4 X 4'

In [ ]:
# vemos como lo ha sacado
Accesorios

['Aire acondicionado',
 'Asientos de cuero',
 'Cerraduras eléctricas',
 'Piloto automático',
 'Sensor de estacionamiento',
 'Sensor de lluvia']

In [ ]:
# ahora vamos a sacar un elemento 'Piloto automático' que ocupa la posición 3
Accesorios.pop(3)

'Piloto automático'

In [ ]:
# vemos como quedó la lista
Accesorios

['Aire acondicionado',
 'Asientos de cuero',
 'Cerraduras eléctricas',
 'Sensor de estacionamiento',
 'Sensor de lluvia']

## *A.copy()*

Crea una copia de la lista *A*.

<font color=red>**Observación:**</font> El mismo resultado puede ser obtenido con el seguinte código:
```
A[:]
```

In [ ]:
# copiamos los elementos de una lista para otra lista
Accesorios_2 = Accesorios.copy()
Accesorios_2

['Aire acondicionado',
 'Asientos de cuero',
 'Cerraduras eléctricas',
 'Sensor de estacionamiento',
 'Sensor de lluvia']

In [ ]:
# trabajamos sobre la lista que hemos creado copiando la lista Accesorios
Accesorios_2.append('4 X 4')
Accesorios_2

['Aire acondicionado',
 'Asientos de cuero',
 'Cerraduras eléctricas',
 'Sensor de estacionamiento',
 'Sensor de lluvia',
 '4 X 4']

In [ ]:
# vemos que no se ha modificado la lista original
Accesorios

['Aire acondicionado',
 'Asientos de cuero',
 'Cerraduras eléctricas',
 'Sensor de estacionamiento',
 'Sensor de lluvia']

In [ ]:
# otra forma de realizar una copia de una lista es:
Accesorios_2 = Accesorios [:]
Accesorios_2
# este método es lo mismo que con la función -copy- "Accesorios_2 = Accesorios.copy()""

['Aire acondicionado',
 'Asientos de cuero',
 'Cerraduras eléctricas',
 'Sensor de estacionamiento',
 'Sensor de lluvia']

In [ ]:
# Ejemplo:
Accesorios_1 = [
    'Llantas de aleación',
    'Cerraduras eléctricas',
    'Piloto automático',
    'Bancos de cuero',
    'Aire acondicionado'
]
# Tenemos que dejar una lista de esta forma:
'''['Airbag',
 'Aire acondicionado',
 'Bancos de cuero',
 'Cerraduras eléctricas',
 'Llantas de aleación',
 'Ventanas eléctricas']'''

Accesorios_1

['Llantas de aleación',
 'Cerraduras eléctricas',
 'Piloto automático',
 'Bancos de cuero',
 'Aire acondicionado']

In [ ]:
# como realizo el proceso correcto sin colocar número de elemento en el método -pop-
# sin colocar que elemento quitar, si no que la intención es quitar el ultimo elemento de la lista
'''
Accesorios_1.append('Airbag')
Accesorios_1.sort()
Accesorios_1.pop()
Accesorios_1.append('Ventanas eléctricas')
Accesorios_1
'''

"\nAccesorios_1.append('Airbag')\nAccesorios_1.sort()\nAccesorios_1.pop()\nAccesorios_1.append('Ventanas eléctricas')\nAccesorios_1\n"

In [ ]:
# Ahora vamos a sumar los elementos llamado 'Airbag'
Accesorios_1.append('Airbag')

In [ ]:
# ordenamos la lista
Accesorios_1.sort()


In [ ]:
# ahora vamos a extraer el último elemento 'Piloto automático' de la lista con el método 'pop'
Accesorios_1.pop()


'Piloto automático'

In [ ]:
# Ahora sumamos el elementos llamado 'Ventanas eléctricas'
Accesorios_1.append('Ventanas eléctricas')

In [ ]:
# finalmente la lista queda:
Accesorios_1

['Airbag',
 'Aire acondicionado',
 'Bancos de cuero',
 'Cerraduras eléctricas',
 'Llantas de aleación',
 'Ventanas eléctricas']

# <font color=green> 4. ESTRUCTURAS DE REPETICIÓN Y CONDICIONALES
---

# 4.1 Instrucción *for*

#### Formato estándar

```
for <variable> in <coleccion>:
    <instrucciones>
```

### Loops con listas

In [ ]:
Accesorios = ['Aire acondicionado',
 'Asientos de cuero',
 'Cerraduras eléctricas',
 'Piloto automático',
 'Sensor de estacionamiento',
 'Sensor de lluvia']
Accesorios

['Aire acondicionado',
 'Asientos de cuero',
 'Cerraduras eléctricas',
 'Piloto automático',
 'Sensor de estacionamiento',
 'Sensor de lluvia']

In [ ]:
# Recordemos que el bucle 'for' lo que realiza es recorrer o iterar elementos dentro de una colección (lista)
# no tenemos que olvidar de aplicar la indentación ya que nos que indica que nos encontramos dentro del buble
for item in Accesorios:
  print(item)
# Tengamos en cuanta que cuando imprime es una secuencia de palabras no una lista

Aire acondicionado
Asientos de cuero
Cerraduras eléctricas
Piloto automático
Sensor de estacionamiento
Sensor de lluvia


###  List comprehensions

https://docs.python.org/3.6/tutorial/datastructures.html#list-comprehensions

*range()* -> https://docs.python.org/3.6/library/functions.html#func-range

In [ ]:
# Función -range()- En lugar de ser una función, range en realidad es un tipo de secuencia inmutable,
# este método nos ayuda a creas valores secuenciales, simulando una colección de valores como una lista,
# pero de forma ordenada

# Ejemplo: creamos 10 elementos (desde la posición 0 al 9)
range(10)


range(0, 10)

In [ ]:
# Aquí obtenemos una lista de 10 valores de forma ordenada del 0 al 9
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
# imprimirá los elementos que tenemos en range(10) todos al cuadrado
for i in range(10):
  print(i ** 2)

0
1
4
9
16
25
36
49
64
81


In [ ]:
# creamos una lista para guardar los elementos con el método -append- dentro del bucle 'for'
cuadrado = []
for i in range(10):
  cuadrado.append(i ** 2)
cuadrado

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [ ]:
# A éste proceso lo conoceremos como -List comprehensions- (Lista por comprensión)
# realizamos lo mismo, pero en menos líneas de código

cuadrado = [i ** 2 for i in range(10)]


In [ ]:
cuadrado

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [ ]:
'''
RECORDEMOS que en el campo <variable>, podemos tener cualquier nombre válido en Python,
en el campo <colección> podemos tener cualquier objeto iterable
(listas, diccionarios, tuplas, etc.) y para iniciar las <instrucciones>,
primero debemos indentar el código
 '''

'\nRECORDEMOS que en el campo <variable>, podemos tener cualquier nombre válido en Python,\nen el campo <colección> podemos tener cualquier objeto iterable \n(listas, diccionarios, tuplas, etc.) y para iniciar las <instrucciones>, \nprimero debemos indentar el código\n '

# 4.2 Loops anidados

In [ ]:
# Observamos que los elementos de la lista datos, son más listas
datos = [
    ['Llantas de aleación', 'Cerraduras eléctricas', 'Piloto automático', 'Asientos de cuero', 'Aire acondicionado', 'Sensor de estacionamiento', 'Sensor de crepúsculo', 'Sensor de lluvia'],
    ['Central multimedia', 'Techo panorámico', 'Frenos ABS', '4 X 4', 'Panel digital', 'Piloto automático', 'Asientos de cuero', 'Cámara de estacionamiento'],
    ['Piloto automático', 'Control de estabilidad', 'Sensor crepuscular', 'Frenos ABS', 'Transmisión automática', 'Asientos de cuero', 'Central multimedia', 'Ventanas eléctricas']
]
datos

[['Llantas de aleación',
  'Cerraduras eléctricas',
  'Piloto automático',
  'Asientos de cuero',
  'Aire acondicionado',
  'Sensor de estacionamiento',
  'Sensor de crepúsculo',
  'Sensor de lluvia'],
 ['Central multimedia',
  'Techo panorámico',
  'Frenos ABS',
  '4 X 4',
  'Panel digital',
  'Piloto automático',
  'Asientos de cuero',
  'Cámara de estacionamiento'],
 ['Piloto automático',
  'Control de estabilidad',
  'Sensor crepuscular',
  'Frenos ABS',
  'Transmisión automática',
  'Asientos de cuero',
  'Central multimedia',
  'Ventanas eléctricas']]

In [ ]:
# Con este 'for' recorremos la lista datos y obtenemos los elementos, que son sublistas
for lista in datos:
  print(lista)

['Llantas de aleación', 'Cerraduras eléctricas', 'Piloto automático', 'Asientos de cuero', 'Aire acondicionado', 'Sensor de estacionamiento', 'Sensor de crepúsculo', 'Sensor de lluvia']
['Central multimedia', 'Techo panorámico', 'Frenos ABS', '4 X 4', 'Panel digital', 'Piloto automático', 'Asientos de cuero', 'Cámara de estacionamiento']
['Piloto automático', 'Control de estabilidad', 'Sensor crepuscular', 'Frenos ABS', 'Transmisión automática', 'Asientos de cuero', 'Central multimedia', 'Ventanas eléctricas']


In [ ]:
# para visualizar los elementos de las sublistas, aplicamos otro bucle for dentro del anterior
# a este proceso se lo conoce como bucle o loops anidados
for lista in datos:
  for iten in lista:
    print(iten)

Llantas de aleación
Cerraduras eléctricas
Piloto automático
Asientos de cuero
Aire acondicionado
Sensor de estacionamiento
Sensor de crepúsculo
Sensor de lluvia
Central multimedia
Techo panorámico
Frenos ABS
4 X 4
Panel digital
Piloto automático
Asientos de cuero
Cámara de estacionamiento
Piloto automático
Control de estabilidad
Sensor crepuscular
Frenos ABS
Transmisión automática
Asientos de cuero
Central multimedia
Ventanas eléctricas


In [ ]:
# En éste proseso lo que realizamos es crear una lista vacia llamada Accesorios,
# y luego realizar una lista única con todos los elementos de las sublistas.

Accesorios = []
for lista in datos:
  for iten in lista:
    Accesorios.append(iten)
Accesorios

['Llantas de aleación',
 'Cerraduras eléctricas',
 'Piloto automático',
 'Asientos de cuero',
 'Aire acondicionado',
 'Sensor de estacionamiento',
 'Sensor de crepúsculo',
 'Sensor de lluvia',
 'Central multimedia',
 'Techo panorámico',
 'Frenos ABS',
 '4 X 4',
 'Panel digital',
 'Piloto automático',
 'Asientos de cuero',
 'Cámara de estacionamiento',
 'Piloto automático',
 'Control de estabilidad',
 'Sensor crepuscular',
 'Frenos ABS',
 'Transmisión automática',
 'Asientos de cuero',
 'Central multimedia',
 'Ventanas eléctricas']

## *set()*

https://docs.python.org/3.6/library/stdtypes.html#types-set

https://docs.python.org/3.6/library/functions.html#func-set

In [ ]:
# Aplicando la función -set- lo que va a pasar es elimionar los elementos duclicados,
# pero si no indicamos donde se tienen que ubicar esos datos,
# no nos arroja los datos en una lista

set(Accesorios)

{'4 X 4',
 'Aire acondicionado',
 'Asientos de cuero',
 'Central multimedia',
 'Cerraduras eléctricas',
 'Control de estabilidad',
 'Cámara de estacionamiento',
 'Frenos ABS',
 'Llantas de aleación',
 'Panel digital',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de crepúsculo',
 'Sensor de estacionamiento',
 'Sensor de lluvia',
 'Techo panorámico',
 'Transmisión automática',
 'Ventanas eléctricas'}

In [ ]:
# Para que los datos sin repetir quede convertido en una lista, lo realizamos de la siguiente forma:
list(set(Accesorios))

['Asientos de cuero',
 'Aire acondicionado',
 'Techo panorámico',
 'Frenos ABS',
 'Sensor crepuscular',
 'Sensor de lluvia',
 'Central multimedia',
 'Cerraduras eléctricas',
 'Piloto automático',
 'Panel digital',
 'Transmisión automática',
 'Ventanas eléctricas',
 'Llantas de aleación',
 'Sensor de estacionamiento',
 '4 X 4',
 'Control de estabilidad',
 'Cámara de estacionamiento',
 'Sensor de crepúsculo']

In [ ]:
# Ejemplo: de la lista datos hay que recorrer los elementos y obtener una lista nueva con cada un de los item de las sublistas
# veremos formas diferentes de poder realizar iterado en listas de listas
datos = [
    ['A', 'B', 'C'],
    ['D', 'E', 'F'],
    ['G', 'H', 'I']
]
# bucle o loops anidado
result = []
for lista in datos:
    for iten in lista:
        result.append(iten)
result

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I']

In [ ]:
# Un bucle para recorrer los datos y sumarlos a una lista
result_2 = []
for lista in datos:
    result_2 += lista
result_2

'''
Recuerda que el operador de suma (+), cuando se aplica a dos listas,
devuelve la concatenación de estas listas.
'''

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I']

In [ ]:
# Método 'List comprehensions'
[iten for lista in datos for iten in lista]

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I']

### List comprehensions

In [ ]:
# Aplicamos el método 'List comprehensions' una forma de aplicar los mismo pero en menos líneas de código
Accesorios = list(set([iten for lista in datos for iten in lista ]))
Accesorios

['Asientos de cuero',
 'Aire acondicionado',
 'Techo panorámico',
 'Frenos ABS',
 'Sensor crepuscular',
 'Sensor de lluvia',
 'Central multimedia',
 'Cerraduras eléctricas',
 'Piloto automático',
 'Panel digital',
 'Transmisión automática',
 'Ventanas eléctricas',
 'Llantas de aleación',
 'Sensor de estacionamiento',
 '4 X 4',
 'Control de estabilidad',
 'Cámara de estacionamiento',
 'Sensor de crepúsculo']

# 4.3 Instrucción *if*

#### Formato estándar

```
if <condicion>:
     <instrucciones en caso la condición sea verdadera>
```

### Operadores de comparación: $==$, $!=$, $>$, $<$, $>=$, $<=$
### y
### Operadores lógicos: $and$, $or$, $not$

In [ ]:
# 1º objeto de la lista - Nombre del vehículo
# 2º objeto de la lista - Año de fabricación
# 3º objeto de la lista - Vehículo es cero km?

datos = [
    ['Jetta Variant', 2003, False],
    ['Passat', 1991, False],
    ['Crossfox', 1990, False],
    ['DS5', 2019, True],
    ['Aston Martin DB4', 2006, False],
    ['Palio Weekend', 2012, False],
    ['A5', 2019, True],
    ['Série 3 Cabrio', 2009, False],
    ['Dodge Jorney', 2019, False],
    ['Carens', 2011, False]
]
datos

In [ ]:
# lo primero que hacemos es recorrer los datos de la lista datos
# luego verificamos cual tiene el valor True
# creamos una lista vacía para guardar los valores True obtenidos

cero_km_T = []
for lista in datos:
  if (lista[-1] == True):
    cero_km_T.append(lista)

cero_km_T

[['DS5', 2019, True], ['A5', 2019, True]]

### List comprehensions

In [ ]:
# Recordamos que lo pimero que tenemos que colocar es la variable que vamos almacenar dentro de la lista
# Luego colocamos la sentencia 'for' y luego el 'if', siempre mantener el orden
[lista for lista in datos  if (lista[-1] == True)]

[['DS5', 2019, True], ['A5', 2019, True]]

# 4.4 Instrucciones *if-else* y *if-elif-else*

#### Formato estándar

```
if <condicion>:
    <instrucciones en caso la condición sea verdadera>
else:
    <instrucciones en caso la condición no sea verdadera>
```

In [ ]:
cero_km_T, cero_km_F = [], []
# en la instruccion 'if' - 'else' lo que pregunta es: -si- cumple la 1ra codición, guardamos en cero_km_T.append(lista)
# si no cumple la primera condición y cumple la segunda condición, lo guarda en cero_km_F.append(lista)
for lista in datos:
  if (lista[-1] == True):
    cero_km_T.append(lista)
  else:
    cero_km_F.append(lista)



In [ ]:
cero_km_T

[['DS5', 2019, True], ['A5', 2019, True]]

In [ ]:
cero_km_F

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

#### Formato estándar

```
if <condicion 1>:
    <instrucciones en caso la condición 1 sea verdadera>
elif <condicion 2>:
    <instrucciones en caso la condición 2 sea verdadera>
elif <condicion 3>:
    <instrucciones en caso la condición 3 sea verdadera>
                        .
                        .
                        .
else:
    <instrucciones en caso las condiciones anteriores no sean verdaderas>
```

In [ ]:
datos

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['DS5', 2019, True],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [ ]:
# Ayuda para saber como funciona el "and"
print('AND')
print(f'(True and True) el resultado es: {True and True}')
print(f'(True and False) el resultado es: {True and False}')
print(f'(False and True) el resultado es: {False and True}')
print(f'(False and False) el resultado es: {False and False}')

In [ ]:
# Ayuda para saber como funciona el "or"
print('OR')
print(f'(True or True) el resultado es: {True or True}')
print(f'(True or False) el resultado es: {True or False}')
print(f'(False or True) el resultado es: {False or True}')
print(f'(False or False) el resultado es: {False or False}')

In [ ]:
# Creamos 3 listas para completar con ellas los autos de diferentes modelos
A,B,C = [], [], []

for lista in datos:
  if(lista[-2] < 2000):
    A.append(lista)
  elif(lista[-2] >= 2000 and lista[-2] < 2010):
    B.append(lista)
  else:
     C.append(lista)


In [ ]:
# Podemos ver que en la lista 'A', se guardaron los vehículos según la primera condición
A

[['Passat', 1991, False], ['Crossfox', 1990, False]]

In [ ]:
# Podemos ver que en la lista 'B', se guardaron los vehículos según la segunda condición
B

[['Jetta Variant', 2003, False],
 ['Aston Martin DB4', 2006, False],
 ['Série 3 Cabrio', 2009, False]]

In [ ]:
# Podemos ver que en la lista 'C', se guardaron los vehículos que no cumplían ninguna de las dos condiciones
C

[['DS5', 2019, True],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [ ]:
# aplicado de otra si cumple la condición para la sentencia 'elif'
for lista in datos:
  if(lista[-2] < 2000):
    A.append(lista)
  elif( 2000 <= lista[-2] < 2010):
    B.append(lista)
  else:
     C.append(lista)

# <font color=green> 5. NUMPY BÁSICO
---

Numpy es la abreviación de Numerical Python y es uno de los paquetes más importantes para procesamiento numérico en Python. Numpy ofrece la base para la mayoría de los paquetes de aplicaciones científicas que usen datos numéricos en Python (estructuras de datos y algoritmos). Pueden destacarse los siguientes recursos que el paquete Numpy contiene:

- Un poderoso objeto array multidimensional;
- Funciones matemáticas sofisticadas para operaciones con arrays sin la necesidad de utilización de bucles *for*;
- Recursos de algebra linear y generación de números aleatórios

Además de sus obvios usos científicos, el paquete NumPy también es muy utilizado en análisis de datos como un eficiente contenedor multidimensional de datos genéricos para transporte entre diversos algoritmos y bibliotecas en Python.

**Versión:** 1.18.4

**Instalación:** https://scipy.org/install.html

**Documentación:** https://numpy.org/doc/1.18/

### Paquetes

Existen diversos paquetes Python disponibles para download en internet. Cada paquete tiene como objetivo la solución de determinado tipo de problema y para esto son desarrollados nuevos tipos, funciones y métodos.

Algunos paquetes son bastante utilizados en un contexto de ciencia de datos, como por ejemplo:

- Numpy
- Pandas
- Scikit-learn
- Matplotlib

Algunos paquetes no son distribuidos en la instalación estándar de Python. En este caso debemos instalar los paquetes que necesitamos en nuestro sistema para poder utilizar sus funcionalidades.

### Importando todo el paquete

In [ ]:
# Automáticamente todos los métodos que existan dentro de la biblioteca, quedan disponibles
import numpy

https://numpy.org/doc/1.16/reference/generated/numpy.arange.html

In [ ]:
# Método -array- sirve para generar una lista de valores secuenciales de un determinado tamaño
numpy.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Importando todo el paquete y asignándole un nuevo nombre

In [ ]:
# Al paquete 'numpy' le asignamos el nombre de 'np'
import numpy as np


In [ ]:
# invocamos el método arange con la palabra 'np' = que si ponemos "numpy.arange(10)"
# es más fácil y optimiza nuestro código
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Importando parte del paquete

In [ ]:
# Importemos el método -arange- desde -numpy- para no tener que importar toda la biblioteca
# En este caso solo tendríamos disponible el método arange de la biblioteca
from numpy import arange

In [ ]:
# Invocamos solo el método -arange- y y obtenemos un arange de numpy de 10 elementos
arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 5.1 Creando arrays Numpy

In [2]:
# Importamos la biblioteca -numpy- con asignación de nombre 'np'
import numpy as np


### A partir de listas

https://numpy.org/doc/1.16/user/basics.creation.html

In [ ]:
# Creamos un array de numpy, todo lo que colocamos dentro del paréntesis es lo que
# se convertirá en un "arrays de numpy"
km = np.array([1000,2300,4987,1500])

In [ ]:
km

array([1000, 2300, 4987, 1500])

In [ ]:
# Al ver que type es km, vemos que es un "arrays de numpy"
type(km)

numpy.ndarray

https://numpy.org/doc/1.16/user/basics.types.html

In [ ]:
# Para ver que tipos de datos que contiene el 'arrays de numpy = km'
# método -dtype- es para ver el tipo de dato
km.dtype

dtype('int64')

### A partir de datos externos

https://numpy.org/doc/1.16/reference/generated/numpy.loadtxt.html

In [ ]:
# para crear un array de datos externos utilizamos el método -loadtxt-
# forma de generar array a partir de array numpy, a partir datos desde un archivo de texto.
# una de las virtudes de 'arrays numpys'es generar archivos de más de una dimensión
km = np.loadtxt(fname = 'carros-km.txt', dtype= int)

In [ ]:
# en éste caso tenemos un archivo unidimensional, porque solo tiene números, ni filas ni columnas
# es solo una secuencia de números
km

array([ 44410,   5712,  37123,      0,  25757,  10728,      0,  77599,
        99197,  37978,  12859,   8052,  89773,      0,  41457, 115607,
        46449,      0,  37086,  15173, 101193,      0,  98079, 102959,
            0,      0,   5795,      0,  58848,  94381,  30163,  53332,
        17720,  33808,  90684,  43975,      0,      0,   5526,      0,
        93415,  40762,      0,  86302,      0,   9755,  69945,   2395,
            0,  80349,  85554,  50496,  67716,  93947,  35345,  81007,
       119513,      0,      0,      0,      0,      0, 118895,  48509,
       100912,  95649,      0,  90495,      0,  29132,  23802,  84992,
        54395,  26731,  44329, 118236, 113808,    610,      0,      0,
        12887,  79607,  90924,  42733,      0,      0, 117714, 113885,
            0,  30511,  74867, 119760,   8356,  64247,  88661,   4539,
       110116,  33215,  92001,      0,  81708,  70641,      0,  91277,
        26544,  52596,  47503,  89056,  28834, 110564,  56638,  17357,
      

In [ ]:
# el tipo de datos de el arrays es un 'int64' con limites bastante amplios
km.dtype

dtype('int64')

### Arrays con dos dimensiones

In [ ]:
datos = [
    ['Llantas de aleación', 'Cerraduras eléctricas', 'Piloto automático', 'Asientos de cuero', 'Aire acondicionado', 'Sensor de estacionamiento', 'Sensor de crepúsculo', 'Sensor de lluvia'],
    ['Central multimedia', 'Techo panorámico', 'Frenos ABS', '4 X 4', 'Panel digital', 'Piloto automático', 'Asientos de cuero', 'Cámara de estacionamiento'],
    ['Piloto automático', 'Control de estabilidad', 'Sensor crepuscular', 'Frenos ABS', 'Transmisión automática', 'Asientos de cuero', 'Central multimedia', 'Ventanas eléctricas']
]
datos

[['Llantas de aleación',
  'Cerraduras eléctricas',
  'Piloto automático',
  'Asientos de cuero',
  'Aire acondicionado',
  'Sensor de estacionamiento',
  'Sensor de crepúsculo',
  'Sensor de lluvia'],
 ['Central multimedia',
  'Techo panorámico',
  'Frenos ABS',
  '4 X 4',
  'Panel digital',
  'Piloto automático',
  'Asientos de cuero',
  'Cámara de estacionamiento'],
 ['Piloto automático',
  'Control de estabilidad',
  'Sensor crepuscular',
  'Frenos ABS',
  'Transmisión automática',
  'Asientos de cuero',
  'Central multimedia',
  'Ventanas eléctricas']]

In [ ]:
# vamos a convertir el contenido de la lista 'datos' en una "arrays numpy"
Accesorios = np.array(datos)

In [ ]:
# El contenido de esta "arrays numpy" generó un array con mas de una dirección
Accesorios

array([['Llantas de aleación', 'Cerraduras eléctricas',
        'Piloto automático', 'Asientos de cuero', 'Aire acondicionado',
        'Sensor de estacionamiento', 'Sensor de crepúsculo',
        'Sensor de lluvia'],
       ['Central multimedia', 'Techo panorámico', 'Frenos ABS', '4 X 4',
        'Panel digital', 'Piloto automático', 'Asientos de cuero',
        'Cámara de estacionamiento'],
       ['Piloto automático', 'Control de estabilidad',
        'Sensor crepuscular', 'Frenos ABS', 'Transmisión automática',
        'Asientos de cuero', 'Central multimedia', 'Ventanas eléctricas']],
      dtype='<U25')

In [ ]:
# vamos a utilizar el método "shape" para saber cuantas dimensiones tiene el array
# cuando tiene un valor antes de la coma, es porque es de una dimensión
km.shape

(258,)

In [ ]:
# Cuando tiene un número antes y después de la coma, es porque es de dos dimensiones
# el número delante de la coma, es la cantidad de filas
# el número a la derecha de la coma, es la cantidad de columnas
# Podemos decir entonces que el método -shape- es para saber como esta "configurado el arrays"
Accesorios.shape

(3, 8)

### Comparando desempeño con listas

In [ ]:
# Creamos un arrays numpy
np_array = np.arange(1000000)

In [ ]:
# Generamos una lista en python
py_list = list(range(1000000))

In [ ]:
'''
 Calculamos el tiempo que demora en recorrer el arrays numpy "np_array"
 y la lista en python "py_list" realizamodo la misma operación en ambos
 para el 1.000.000 de elementos que la componen
'''

In [ ]:
# Para medir el tiempo vamos a utilizar la palabra reservada -%time-
# la operación que se va a realizar es multiplicar x 2 los elementos del "np_array"
# utilizamos '_' para guardar el último valor o el último cálculo que hemos realizado
%time for _ in range(100): np_array *=2

CPU times: user 57.5 ms, sys: 226 µs, total: 57.7 ms
Wall time: 63.4 ms


In [ ]:
# Vamos a recorrer nuestra lista en python, py_list va a guardar los resultados
# de una list comprehensions, recordamos que es [operación luego el for]
%time for _ in range(100): py_list = [x*2 for x in py_list ]

CPU times: user 9.15 s, sys: 2.12 s, total: 11.3 s
Wall time: 11.4 s


In [ ]:
'''
Con esto queda demostrado que para Bigdata o gran cantidad de datos
conviene utilizar 'arrays numpy' para optimizar

A diferencia de las listas de Python,
que pueden contener tipos variados en una misma secuencia,
arrays Numpy soportan solamente un tipo de dato por vez.

'''

# 5.2 Operaciones aritméticas con arrays Numpy

### Operaciones entre arrays y constantes

In [5]:
km = [44410., 5712., 37123., 0., 25757.]
años = [2003, 1991, 1990, 2019, 2006]

In [ ]:
# vamos a tener un 'TypeError' si queremos sacar los años que tiene el vehículo
# porque no podemos mezclar un tipo de dato 'int' con una 'lista'
edad = 2020 - años

In [7]:
km = np.array([44410., 5712., 37123., 0., 25757.])
años = np.array([2003, 1991, 1990, 2019, 2006])

NameError: ignored

In [ ]:
# si lo realizamos con 'arrays Numpy' podemos realizar la operación
# podemos combinar 'int' con 'arrays Numpy'
edad = 2020 - años

In [ ]:
edad

array([17, 29, 30,  1, 14])

### Operaciones entre arrays

In [ ]:
# realizamos operación aritmética para obtener el km promedio de los vehículos
km_media = km / edad

In [ ]:
km_media

array([2612.35294118,  196.96551724, 1237.43333333,    0.        ,
       1839.78571429])

In [ ]:
# verificamos que el cálculo de los arrays esta bien hecho
444410. / 17

26141.764705882353

### Operaciones con arrays de dos dimensiones

In [9]:
datos = np.array([km, años])

In [ ]:
# el array obtenido es de dos dimensiones
datos

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [ ]:
# utilizamos el método 'shape' para ver de cuantas dimensiones es el arrays
datos.shape

(2, 5)

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [ ]:
# llamamos al array que esta en la posición '0' primera dimensión
datos [0]

array([44410.,  5712., 37123.,     0., 25757.])

In [ ]:
# llamamos al array que esta en la posición '1' segunda dimensión
datos [1]

array([2003., 1991., 1990., 2019., 2006.])

In [ ]:
# realizamos el calculo promedio del km con un único arrays numpy accesando
# separadamente a sus dos dimensiones
km_media = datos[0] / (2020 - datos[1])
km_media
# Ésto es mas práctico cuando tenemos datos agrupados en más de una dimensión

array([2612.35294118,  196.96551724, 1237.43333333,    0.        ,
       1839.78571429])

In [ ]:
# Ejemplo:
# Indice de Masa Corporal - IMC = peso / altura ^ 2 -

peso = np.array([106.0, 68.5, 75.0])
altura = np.array([1.9, 1.53, 1.75])


In [ ]:
IMC = peso / altura **2
IMC

array([29.36288089, 29.26224956, 24.48979592])

# 5.3 Selecciones con arrays Numpy

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [ ]:
# vemos los mismo que tenemos en grande, vamos al 'array datos'
datos

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

![1410-img02.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img02.png)

### Indexación

<font color=red>**Observación:**</font> La indexación tiene inicio en cero.

In [ ]:
# Realizando un repaso de como buscar elementos dentro de una lista, recordamos
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# elemento en la primera posición
contador [0]

0

In [ ]:
# elemento en la última posición
contador [9]

9

In [ ]:
# elemento en la última posición de otra forma
contador [-1]

9

In [ ]:
# cuando lo realizamos en 'datos el array numpy' de 2 dimensiones que tenemos
# buscamos el 1er elemento del array
datos[0]

array([44410.,  5712., 37123.,     0., 25757.])

In [ ]:
# cuando lo realizamos en 'datos el array numpy' de 2 dimensiones que tenemos
# buscamos el 2do elemento del array
datos[1]

array([2003., 1991., 1990., 2019., 2006.])

## <font color=green>**Consejo:**</font>
### *ndarray[ linea ][ columna ]* o *ndarray[ linea, columna ]*

In [ ]:
# para buscar un elemento determinado dentro del array
# una de las formas para poder seleccionar un elemento específico
datos[1][2]

In [ ]:
# otra de las formas para poder seleccionar un elemento específico
datos[1, 2]

1990.0

 ### Particiones

La sintaxis para realizar particiones en un array Numpy es $i : j : k$ donde $i$ es el índice inicial, $j$ es el índice final, y $k$ es el indicador de intervalo ($k\neq0$)

<font color=red>**Observación:**</font> En las particiones (*slices*) el objeto con índice i es **incluído** y el objeto con índice j **no es incluído** en el resultado.

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [ ]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# vamos a realizar un corte dentro del array
# contador [i:j:k]
contador[1:4:]

array([1, 2, 3])

In [ ]:
# partimos el array en otro lugar para ver otro ejemplo
# de la posición 1 a la 7 y se realiza el corte número por medio
contador[1:8:2]

array([1, 3, 5, 7])

In [ ]:
# realizamos el corte con los números pares del array
contador[::2]

array([0, 2, 4, 6, 8])

In [ ]:
# realizamos el corte con los números impares del array
contador[1::2]

array([1, 3, 5, 7, 9])

In [ ]:
# valores del array datos
datos

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [ ]:
# para realizar el corte en un array de dos dimensiones
# datos [línea, columnas]
datos [::, 1:3:]

array([[ 5712., 37123.],
       [ 1991.,  1990.]])

In [ ]:
# vamos a calcular el km promedio con el corte realizado
# vemos que si luego de realizar el corte podemos buscar los valores de la 1ra dimensión
datos [::, 1:3:][0]

array([ 5712., 37123.])

In [ ]:
# buscamos los valores de la 2da dimensión
datos [::, 1:3:][1]

array([1991., 1990.])

In [ ]:
# para poder obtener el km promedio en el corte (de los dos vehículos), sabemos que es km_pro = km / 2020 - año de fabricación
# km =  datos [::, 1:3:][0]
# año de fab = datos [::, 1:3:][1]

datos [::, 1:3:][0] / (2020 -datos [::, 1:3:][1] )

array([ 196.96551724, 1237.43333333])

In [ ]:
# Realizamos el calculo para todos los vehículos
datos[0]/ (2020 - datos[1])

array([2612.35294118,  196.96551724, 1237.43333333,    0.        ,
       1839.78571429])

### Indexación con array booleano

<font color=red>**Observación:**</font> Selecciona un grupo de líneas y columnas siguiendo las etiquetas o un array booleano.

In [ ]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# obtenemos como respuesta True o False
contador > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [ ]:
# otra forma de realizar el corte si quiero cortar el array con estos valores
# recordamos la forma recién vista -contador [i:j:k]-
contador [contador > 5]

array([6, 7, 8, 9])

In [ ]:
datos

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [ ]:
# para obtener los vehículos de año de fabricación mayor al 2000
datos [1] > 2000

array([ True, False, False,  True,  True])

In [ ]:
# realizamos el corte para solo obtener los vehículos con año de fab. mayor a 2000
# datos [líneas, columna]
# otra forma de realizarlo

datos[::, datos [1] > 2000]

array([[44410.,     0., 25757.],
       [ 2003.,  2019.,  2006.]])

In [ ]:
# Ejemplo:
'''
Marca la alternativa que muestra el código que permite la selección del nombre
y el estado civil de las personas del sexo masculino,
sin el uso de operadores lógicos (and y or).
'''
datos_1 = np.array(
    [
        ['Roberto', 'casado', 'masculino'],
        ['Sheila', 'soltero', 'femenino'],
        ['Bruno', 'soltero', 'masculino'],
        ['Rita', 'casado', 'femenino']
    ]
)
datos_1

array([['Roberto', 'casado', 'masculino'],
       ['Sheila', 'soltero', 'femenino'],
       ['Bruno', 'soltero', 'masculino'],
       ['Rita', 'casado', 'femenino']], dtype='<U9')

In [ ]:
# si lo realizamos por parte buscamos primero las personas de sexo masculino
# recordamos que datos_1[i:j:k] (i = filas, j = Columnas y k = saltos)
# buscamos fila por medio que es donde se encuentran los dos nombres masculinos

datos_1[::2]

array([['Roberto', 'casado', 'masculino'],
       ['Bruno', 'soltero', 'masculino']], dtype='<U9')

In [ ]:
# ahora cortamos para obtener el estado civil, teniendo las filas, ahora trabajamos
# con las columnas, es lo mismo que colocar "datos_1[::2, :2:]"
datos_1[::2, :2]

array([['Roberto', 'casado'],
       ['Bruno', 'soltero']], dtype='<U9')

# 5.4 Atributos y métodos de arrays Numpy

### Atributos

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#array-attributes

In [10]:
# Los Atributos nos ayudan a agilizar y optimizar la construcción de nuestros códigos
datos

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

## *ndarray.shape*

Devuelve una tupla con las dimensiones del array.

In [11]:
datos.shape

(2, 5)

## *ndarray.ndim*

Devuelve el número de dimensiones del array.

In [13]:
datos.ndim

2

## *ndarray.size*

Devuelve el número de elementos del array.

In [14]:
# Con el atributo size, conseguimos saber cuántos elementos contiene un array
datos.size

10

## *ndarray.dtype*

Devuelve el tipo de datos de los elementos del array.

In [15]:
# arrays Numpy sólo permiten un tipo de dato por array
datos.dtype

dtype('float64')

## *ndarray.T*

Devuelve el array transpuesto, es decir, convierte líneas en columnas y viceversa.

In [16]:
datos.T

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

In [17]:
# otra forma de realizar un array transpuesto
datos.transpose()

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

### Métodos

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#array-methods

## *ndarray.tolist()*

Devuelve el array como una lista Python.

In [18]:
# Tener en cuenta como diferenciar un Método de un Atributo
# los Métodos llevan ()
datos.tolist()

[[44410.0, 5712.0, 37123.0, 0.0, 25757.0],
 [2003.0, 1991.0, 1990.0, 2019.0, 2006.0]]

## *ndarray.reshape(shape[, order])*

Devuelve un array que contiene los mismos datos con una nueva forma.

In [19]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
# con estos Métodos redimensionamos el array a 5 Filas y 2 Columnas
contador.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [21]:
# en este caso obtenemos el mismo resultado, pidiendo que ordene como en lenguaje C
contador.reshape((5,2) , order = 'C')

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [22]:
# En este caso lo ordena segun el lenguaje 'fortran', tomando los primeros 5 elementos
# para colocarlos como 1er elemento de las filas y los segundos 5, como 2do elemento de las filas

contador.reshape((5,2) , order = 'F')

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [23]:
km = [44410, 5712, 37123, 0, 25757]
años = [2003, 1991, 1990, 2019, 2006]

In [24]:
info_carros = km + años
info_carros

[44410, 5712, 37123, 0, 25757, 2003, 1991, 1990, 2019, 2006]

In [25]:
# transformamos la lista que tenemos en un array y lo redimensionamos con el Método 'reshape()'
np.array(info_carros).reshape((2,5))

array([[44410,  5712, 37123,     0, 25757],
       [ 2003,  1991,  1990,  2019,  2006]])

In [26]:
# Lo ordenamos en 5 filas y 2 columnas y lo ordenamos según el lenguaje 'fortran'
# para que cada vehículo quede junto a su año de fabricación
np.array(info_carros).reshape((5,2), order = 'F')

array([[44410,  2003],
       [ 5712,  1991],
       [37123,  1990],
       [    0,  2019],
       [25757,  2006]])

## *ndarray.resize(new_shape[, refcheck])*

Cambia la forma y el tamaño del array.

In [27]:

# creamos una copia del array datos
datos_new = datos.copy()
datos_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [30]:
# al ser una copa de un array tenemos una referencia con al array original, al ejecutar la sentencia
# nos da una 'ValueError', para no tener ninguna referencia tenemos que adicionamos 'refcheck=False'
# dentro del método para que no tenga referencia con el array original

datos_new.resize((3,5), refcheck=False)

In [31]:
# en la última fila tiene datos en blanco por lo que todavía no le damos un valor
datos_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.],
       [    0.,     0.,     0.,     0.,     0.]])

In [32]:
# en la última fila colocaremos el km promedio
# recordemos que la formula es dato = km / (2020 - año fabricación)

datos_new[2] = datos_new[0] / (2020 - datos_new[1])

In [33]:
datos_new

array([[44410.        ,  5712.        , 37123.        ,     0.        ,
        25757.        ],
       [ 2003.        ,  1991.        ,  1990.        ,  2019.        ,
         2006.        ],
       [ 2612.35294118,   196.96551724,  1237.43333333,     0.        ,
         1839.78571429]])

# 5.5 Estadísticas con arrays Numpy

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#calculation

y

https://numpy.org/doc/1.16/reference/routines.statistics.html

y

https://numpy.org/doc/1.16/reference/routines.math.html

In [4]:
años = np.loadtxt(fname = "carros-años.txt", dtype = int)
km = np.loadtxt(fname = "carros-km.txt")
valor = np.loadtxt(fname = "carros-valor.txt")

In [5]:
# Inspeccionamos la dimensión de años
años.shape

(258,)

https://numpy.org/doc/1.16/reference/generated/numpy.column_stack.html

In [ ]:
# Para convertir en una matriz
# para eso utilizamos la función llamada -column_stack()-
dataset = np.column_stack((años, km, valor))
dataset

In [7]:
# vemos la dimensión de nuestro dataset
dataset.shape

(258, 3)

## *np.mean()*

Devuelve el promedio de los elementos del array a lo largo del eje especificado.

In [12]:
# con la función mean() vamos a calcular la media de una de las columnas
# utilizamos el atributo 'axis' vamos a tener que determinar si lo vamos
# a buscar horizontal = 0, vertical = 1

np.mean(dataset, axis = 0)

array([ 2007.74806202, 44499.41472868, 98960.51310078])

In [ ]:
np.mean(dataset, axis = 1)

In [14]:
# otra forma de realizarlo es con partición np.mean(dataset, [lineas, columnas])
# observamos que es el mismo valor que obtenemos en el primer ejemplo
# nos trea el promedio de la segunda columna
np.mean(dataset [::,1])

44499.41472868217

In [15]:
# Calculamos el valor de la 3ra columna
np.mean(dataset [::,2])

98960.51310077519

In [22]:
# Ejemplo de las diferentes formas de sacar promedio

edades = np.array([10, 23, 45, 34, 25])


In [26]:
'''
Recordando que, el argumento axis puede que necesite configurarse cuando
trabajamos con arrays de más de una dimensión.
'''
np.mean(edades)

27.4

In [25]:
'''
Esta forma no se presentó en los ejemplos anteriores, pero también es una forma válida
de obtener el promedio de los datos en un array Numpy.
'''
edades.mean()

27.4

In [27]:
'''
También es posible obtener el promedio con una combinación de funciones de Numpy.
La media aritmética se define como la relación entre la suma de todos
los valores y el número de valores involucrados en la suma
'''
np.sum(edades)/ edades.size

27.4

## *np.std()*

Devuelve la desviación estándar de los elementos del array a lo largo del eje especificado.

In [16]:
# Calculamos la desviación estándar
np.std(dataset [::,2])

29754.101150388564

## *ndarray.sum()*

Devuelve la suma de los elementos del array a lo largo del eje especificado.

In [17]:
# realizamos la sumatoria de las columnas con la función -sum()-
# lo realizamos también con el atributo axis para que nos de el resultado en una fila
dataset.sum(axis = 0)

array([  517999.        , 11480849.        , 25531812.37999999])

In [18]:
# también lo podemos hacer con particiones 'dataset[lineas, columnas]'
# y luego la función -sum()-
dataset[::,1].sum()

11480849.0

## *np.sum()*

Devuelve la suma de los elementos del array a lo largo del eje especificado.

In [19]:
# otra formato para realizar la suma
np.sum(dataset, axis = 0)

array([  517999.        , 11480849.        , 25531812.37999999])

In [20]:
# lo realizamos también de forma particionado 'np.sum(dataset[lineas, columnas])'
np.sum(dataset [::, 2])

25531812.38

In [21]:
# adelantando un poco sobre la biblioteca Pandas!!
# con este ejemplo vamos a sacar el promedio de km y valor del vehículo teniendo en cuenta
# el año de fabricación
import pandas as pd

df = pd.DataFrame(data=dataset, columns=["años", "km", "valores"])
result = df.groupby('años').mean()
print(result)



                  km        valores
años                               
1990.0  72083.666667   96116.206667
1991.0  47036.444444   93420.658889
1992.0  51283.000000   90670.667500
1993.0  55384.250000   93357.635000
1994.0  70260.777778   96623.326667
1995.0  71289.714286   86117.702857
1996.0  50926.100000   98619.528000
1997.0  71897.000000   96852.883333
1998.0  71828.000000   97801.913333
1999.0  39075.500000   98675.220000
2000.0  98921.000000  112101.906667
2001.0  69583.750000  105120.757500
2002.0  59268.545455   89327.512727
2003.0  56926.571429  111672.687143
2004.0  62735.800000   82253.320000
2005.0  58052.500000  117836.888333
2006.0  45569.750000   91200.577500
2007.0  59986.750000  101135.170000
2008.0  61647.833333  103123.380000
2009.0  48694.000000  110470.614286
2010.0  79227.333333   98001.035000
2011.0  53031.000000  106613.244000
2012.0  40817.500000   89212.192500
2013.0  39021.777778  105672.001111
2014.0  57461.500000   87228.613333
2015.0  61032.125000  103795